# Generated by Django 5.2.1 on 2025-05-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_event_has_seats_ticket_entry_time_ticket_exit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de escaneos'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last_digits',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de tarjeta'),
        ),
    ]