# Generated by Django 5.2.1 on 2025-05-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_add_payment_card_fields_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Música'), ('sports', 'Deportes'), ('culture', 'Cultura'), ('education', 'Educación'), ('business', 'Negocios'), ('other', 'Otro')], default='other', max_length=50, verbose_name='Categoría'),
        ),
    ]
